<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- main arm base  -->
    <xacro:property name="cuboid_mass" value="0.5" />
    <xacro:property name="cuboid_length" value="0.1" />
    <xacro:property name="cuboid_width" value="0.1" />
    <xacro:property name="cuboid_height" value="0.02" />
    
    <!-- cylinders for forearm and hand -->
    <xacro:property name="cylinder_mass" value="0.3" />
    <xacro:property name="cylinder_length" value="0.3" />
    <xacro:property name="cylinder_radius" value="0.02" />

    <!-- robot links -->

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${cuboid_length} ${cuboid_width} ${cuboid_height}" />
            </geometry>
            <origin xyz="0 0 ${cuboid_height / 2}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${cuboid_length} ${cuboid_width} ${cuboid_height}" />
            </geometry>
            <origin xyz="0 0 ${cuboid_height / 2}" rpy="0 0 0" />
        </collision>
        <xacro:cuboid_inertia m="${cuboid_mass}" l="${cuboid_length * 2}" w="${cuboid_width * 2}" h="${cuboid_height * 2}" 
                              xyz="0 0 ${cuboid_height / 2.0}" rpy="0 0 0" />
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${cylinder_radius}" length="${cylinder_length}" />
            </geometry>
            <origin xyz="0 0 ${(cylinder_length / 2)}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${cylinder_radius}" length="${cylinder_length}" />
            </geometry>
            <origin xyz="0 0 ${(cylinder_length / 2)}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="${cylinder_mass}" r="${cylinder_radius * 2}" h="${cylinder_length * 2}" 
                                xyz="0 0 ${(cylinder_length / 2)}" rpy="0 0 0" />
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${cylinder_radius}" length="${cylinder_length}" />
            </geometry>
            <origin xyz="0 0 ${(cylinder_length / 2)}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${cylinder_radius}" length="${cylinder_length}" />
            </geometry>
            <origin xyz="0 0 ${(cylinder_length / 2)}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="${cylinder_mass}" r="${cylinder_radius * 2}" h="${cylinder_length * 2}" 
                                xyz="0 0 ${(cylinder_length / 2)}" rpy="0 0 0" />
    </link>

    <!-- arm joints -->

    <joint name="arm_base_forearm_joint" type="revolute">
        <limit lower="0" upper="${pi / 2}" effort="100" velocity="100" />
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${cuboid_height}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <limit lower="0" upper="${pi / 2}" effort="100" velocity="100" />
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${cylinder_length}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

</robot>